/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClientConfig {
  width: number
  height: number
  title: string
  vsync: boolean
}
export declare function useVulkan(): boolean
export declare function getBuildMode(): string
export declare function createClient(): DesktopClient
export declare class DesktopClient {
  constructor()
  initialize(jsConfig?: ClientConfig | undefined | null): void
  run(): void
  cleanup(): void
}
